CREATE TABLE IF NOT EXISTS pokemon(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
imagem VARCHAR(255),
nome VARCHAR(20),
altura FLOAT(4,1),
peso FLOAT(5,2),
descricao TEXT);

CREATE TABLE IF NOT EXISTS habilidades(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(20),
descricao TEXT);

CREATE TABLE IF NOT EXISTS tipos(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
tipo VARCHAR(20));

CREATE TABLE IF NOT EXISTS tem_habilidades(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
id_habilidades INTEGER,
id_pokemon INTEGER,
FOREIGN KEY (id_habilidades) REFERENCES habilidades(id),
FOREIGN KEY (id_pokemon) REFERENCES pokemon(id));

CREATE TABLE IF NOT EXISTS tem_tipo(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
id_tipo INTEGER,
id_pokemon INTEGER,
FOREIGN KEY (id_tipo) REFERENCES tipos(id),
FOREIGN KEY (id_pokemon) REFERENCES pokemon(id));

DELIMITER //
CREATE PROCEDURE novo_tipo(
IN p_nv_tipo VARCHAR(20)
)
BEGIN
DECLARE cnt_tipo INT;
SELECT COUNT(*) INTO cnt_tipo FROM tipos WHERE tipo=p_nv_tipo;
IF cnt_tipo > 0 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Já existe esse tipo cadastrado';
END IF;
INSERT INTO tipos(tipo) VALUES (p_nv_tipo);
END //

DELIMITER ;
